server:
  httplisten:  "0.0.0.0:80"

log:
  encoding:       "json"
  outputpaths:
    - "log/app.log"
    - "stdout"
  level:          "debug"
  initialfields:
    app:          "carizza"

db:
  pg:
    dialect:        "postgres"
    dsn:            "host=db port=5432 dbname=car_catalog user=postgres password=1gjcnuhtc1! sslmode=disable"
    islogmode:      True
    isautomigrate:  True
  redis:
    addrs:
      - "redis:6379"
    login:    ""
    password: ""
    dbname:   0

jwtsigningkey: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwtexpiration: 72
sessionlifetime: 96
